name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make this app better for the Atlanta community.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... OR I need a way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - User Interface / Design
        - Search & Filtering
        - Map & Location Features
        - Accessibility
        - Performance
        - Mobile Experience
        - Data Display
        - New Page or Section
        - Integration with External Service
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-impact
    attributes:
      label: User Impact
      description: Who would benefit from this feature?
      options:
        - All users
        - Mobile users
        - Desktop users
        - Users with disabilities
        - Non-English speakers
        - Power users
        - First-time users
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Alternatively, users could...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: If you have examples from other apps, mockups, or sketches, please share them here
      placeholder: Drag and drop images or paste URLs
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve experience
        - Important for usability
        - Critical for accessibility
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: Any additional details...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to ensure this is not a duplicate
          required: true
        - label: This feature would benefit the Atlanta community using this food resource app
          required: true
